export const accountClasses = [
  { code: "1", label: "Ressources durables", type: "balance" },
  { code: "2", label: "Actif immobilise", type: "balance" },
  { code: "3", label: "Stocks", type: "balance" },
  { code: "4", label: "Tiers", type: "balance" },
  { code: "5", label: "Tresorerie", type: "balance" },
  { code: "6", label: "Charges des activites ordinaires", type: "income" },
  { code: "7", label: "Produits des activites ordinaires", type: "income" },
  { code: "8", label: "Autres charges et autres produits", type: "income" },
  { code: "9", label: "Engagements et comptabilite analytique", type: "off_balance" }
];

const accountGroups = [
  ["10", "Capital", "equity"],
  ["11", "Reserves", "equity"],
  ["12", "Report a nouveau", "equity"],
  ["13", "Resultat net de l'exercice", "equity"],
  ["14", "Subventions d'investissement", "equity"],
  ["15", "Provisions reglementees et fonds assimiles", "equity"],
  ["16", "Emprunts et dettes assimilees", "liability"],
  ["17", "Dettes de credit-bail et contrats assimiles", "liability"],
  ["18", "Dettes liees a des participations", "liability"],
  ["19", "Provisions financieres pour risques et charges", "liability"],
  ["20", "Charges immobilisees", "asset"],
  ["21", "Immobilisations incorporelles", "asset"],
  ["22", "Terrains", "asset"],
  ["23", "Batiments, installations techniques et agencements", "asset"],
  ["24", "Materiel", "asset"],
  ["25", "Avances et acomptes verses sur immobilisations", "asset"],
  ["26", "Titres de participation", "asset"],
  ["27", "Autres immobilisations financieres", "asset"],
  ["28", "Amortissements", "contra_asset"],
  ["29", "Provisions pour depreciation", "contra_asset"],
  ["31", "Marchandises", "asset"],
  ["32", "Matieres premieres et fournitures liees", "asset"],
  ["33", "Autres approvisionnements", "asset"],
  ["34", "Produits en cours", "asset"],
  ["35", "Services en cours", "asset"],
  ["36", "Produits finis", "asset"],
  ["37", "Produits intermediaires et residuels", "asset"],
  ["38", "Stocks en cours de route, consignation ou depot", "asset"],
  ["39", "Depreciations des stocks", "contra_asset"],
  ["40", "Fournisseurs et comptes rattaches", "liability"],
  ["41", "Clients et comptes rattaches", "asset"],
  ["42", "Personnel", "liability"],
  ["43", "Organismes sociaux", "liability"],
  ["44", "Etat et collectivites publiques", "liability"],
  ["45", "Organismes internationaux", "asset"],
  ["46", "Associes-groupe", "liability"],
  ["47", "Debiteurs et crediteurs divers", "asset"],
  ["48", "Creances et dettes hors activites ordinaires", "asset"],
  ["49", "Depreciations et risques provisionnes tiers", "contra_asset"],
  ["50", "Titres de placement", "asset"],
  ["51", "Valeurs a encaisser", "asset"],
  ["52", "Banques", "asset"],
  ["53", "Etablissements financiers et assimiles", "asset"],
  ["54", "Instruments de tresorerie", "asset"],
  ["56", "Banques, credits de tresorerie et d'escompte", "liability"],
  ["57", "Caisse", "asset"],
  ["58", "Regies d'avances, accreditifs et virements internes", "asset"],
  ["59", "Depreciations et risques provisionnes de tresorerie", "contra_asset"],
  ["60", "Achats et variations de stocks", "expense"],
  ["61", "Transports", "expense"],
  ["62", "Services exterieurs A", "expense"],
  ["63", "Services exterieurs B", "expense"],
  ["64", "Impots et taxes", "expense"],
  ["65", "Autres charges", "expense"],
  ["66", "Charges de personnel", "expense"],
  ["67", "Frais financiers et charges assimilees", "expense"],
  ["68", "Dotations aux amortissements", "expense"],
  ["69", "Dotations aux provisions", "expense"],
  ["70", "Ventes", "revenue"],
  ["71", "Subventions d'exploitation", "revenue"],
  ["72", "Production immobilisee", "revenue"],
  ["73", "Variations de stocks de biens et services produits", "revenue"],
  ["75", "Autres produits", "revenue"],
  ["77", "Revenus financiers et assimiles", "revenue"],
  ["78", "Transferts de charges", "revenue"],
  ["79", "Reprises de provisions", "revenue"],
  ["81", "Valeurs comptables des cessions d'immobilisations", "expense"],
  ["82", "Produits des cessions d'immobilisations", "revenue"],
  ["83", "Charges hors activites ordinaires", "expense"],
  ["84", "Produits hors activites ordinaires", "revenue"],
  ["85", "Dotations hors activites ordinaires", "expense"],
  ["86", "Reprises hors activites ordinaires", "revenue"],
  ["87", "Participation des travailleurs", "expense"],
  ["88", "Subventions d'equilibre", "revenue"],
  ["89", "Impots sur le resultat", "expense"],
  ["90", "Engagements obtenus et accordes", "off_balance"],
  ["91", "Contreparties des engagements", "off_balance"],
  ["92", "Comptes reflechis", "off_balance"],
  ["94", "Comptes de couts", "off_balance"],
  ["95", "Comptes de stocks analytiques", "off_balance"],
  ["96", "Ecarts sur couts preetablis", "off_balance"],
  ["97", "Differences de traitement comptable", "off_balance"],
  ["98", "Comptes de resultats analytiques", "off_balance"],
  ["99", "Liaisons internes", "off_balance"]
];

const detailedAccounts = [
  ["101", "Capital social", "equity"],
  ["102", "Capital par dotation", "equity"],
  ["103", "Capital personnel", "equity"],
  ["104", "Compte de l'exploitant", "equity"],
  ["105", "Primes liees aux capitaux propres", "equity"],
  ["106", "Ecarts de reevaluation", "equity"],
  ["109", "Actionnaires, capital souscrit non appele", "contra_equity"],
  ["111", "Reserve legale", "equity"],
  ["112", "Reserves statutaires ou contractuelles", "equity"],
  ["118", "Autres reserves", "equity"],
  ["121", "Report a nouveau crediteur", "equity"],
  ["129", "Report a nouveau debiteur", "contra_equity"],
  ["131", "Resultat net: benefice", "equity"],
  ["139", "Resultat net: perte", "contra_equity"],
  ["141", "Subventions d'equipement", "equity"],
  ["161", "Emprunts obligataires", "liability"],
  ["162", "Emprunts aupres des etablissements de credit", "liability"],
  ["164", "Avances recues et comptes courants bloques", "liability"],
  ["165", "Depots et cautionnements recus", "liability"],
  ["166", "Interets courus sur emprunts", "liability"],
  ["168", "Autres emprunts et dettes", "liability"],
  ["191", "Provisions pour litiges", "liability"],
  ["196", "Provisions pour pensions et obligations similaires", "liability"],
  ["201", "Frais d'etablissement", "asset"],
  ["211", "Frais de recherche et developpement", "asset"],
  ["212", "Brevets, licences et droits similaires", "asset"],
  ["213", "Logiciels", "asset"],
  ["215", "Fonds commercial", "asset"],
  ["221", "Terrains agricoles", "asset"],
  ["222", "Terrains nus", "asset"],
  ["223", "Terrains batis", "asset"],
  ["231", "Batiments industriels et commerciaux", "asset"],
  ["234", "Installations techniques", "asset"],
  ["235", "Amenagements de bureaux", "asset"],
  ["241", "Materiel et outillage", "asset"],
  ["244", "Materiel et mobilier", "asset"],
  ["245", "Materiel de transport", "asset"],
  ["261", "Titres de participation", "asset"],
  ["271", "Prets et creances non commerciales", "asset"],
  ["272", "Prets au personnel", "asset"],
  ["275", "Depots et cautionnements verses", "asset"],
  ["281", "Amortissements des immobilisations incorporelles", "contra_asset"],
  ["284", "Amortissements du materiel", "contra_asset"],
  ["291", "Depreciation des immobilisations incorporelles", "contra_asset"],
  ["294", "Depreciation de materiel", "contra_asset"],
  ["311", "Marchandises A", "asset"],
  ["321", "Matieres A", "asset"],
  ["331", "Matieres consommables", "asset"],
  ["334", "Fournitures de bureau", "asset"],
  ["335", "Emballages", "asset"],
  ["341", "Produits en cours", "asset"],
  ["352", "Prestations de services en cours", "asset"],
  ["361", "Produits finis A", "asset"],
  ["381", "Marchandises en cours de route", "asset"],
  ["391", "Depreciations des stocks de marchandises", "contra_asset"],
  ["401", "Fournisseurs, dettes en compte", "liability"],
  ["402", "Fournisseurs, effets a payer", "liability"],
  ["408", "Fournisseurs, factures non parvenues", "liability"],
  ["409", "Fournisseurs debiteurs", "asset"],
  ["411", "Clients", "asset"],
  ["412", "Clients, effets a recevoir", "asset"],
  ["416", "Creances clients litigieuses ou douteuses", "asset"],
  ["418", "Clients, produits a recevoir", "asset"],
  ["419", "Clients crediteurs", "liability"],
  ["421", "Personnel, avances et acomptes", "asset"],
  ["422", "Personnel, remunerations dues", "liability"],
  ["428", "Personnel, charges a payer et produits a recevoir", "liability"],
  ["431", "Securite sociale", "liability"],
  ["433", "Autres organismes sociaux", "liability"],
  ["438", "Organismes sociaux, charges a payer", "liability"],
  ["441", "Etat, impot sur les benefices", "liability"],
  ["442", "Etat, autres impots et taxes", "liability"],
  ["443", "Etat, TVA facturee", "liability"],
  ["444", "Etat, TVA due ou credit de TVA", "liability"],
  ["445", "Etat, TVA recuperable", "asset"],
  ["447", "Etat, impots retenus a la source", "liability"],
  ["461", "Associes, operations sur le capital", "liability"],
  ["462", "Associes, comptes courants", "liability"],
  ["471", "Comptes d'attente", "asset"],
  ["476", "Charges constatees d'avance", "asset"],
  ["477", "Produits constates d'avance", "liability"],
  ["481", "Fournisseurs d'investissements", "liability"],
  ["491", "Depreciations des comptes clients", "contra_asset"],
  ["501", "Titres du Tresor et bons de caisse court terme", "asset"],
  ["502", "Actions", "asset"],
  ["503", "Obligations", "asset"],
  ["511", "Effets a encaisser", "asset"],
  ["512", "Banques", "asset"],
  ["513", "Cheques a encaisser", "asset"],
  ["521", "Banques locales", "asset"],
  ["522", "Banques autres Etats region", "asset"],
  ["531", "Cheques postaux", "asset"],
  ["532", "Tresor", "asset"],
  ["561", "Credits de tresorerie", "liability"],
  ["571", "Caisse siege social", "asset"],
  ["581", "Regies d'avance", "asset"],
  ["585", "Virements de fonds", "asset"],
  ["601", "Achats de marchandises", "expense"],
  ["602", "Achats de matieres premieres", "expense"],
  ["603", "Variations des stocks de biens achetes", "expense"],
  ["604", "Achats stockes de matieres et fournitures", "expense"],
  ["605", "Autres achats", "expense"],
  ["608", "Achats d'emballages", "expense"],
  ["611", "Transports sur achats", "expense"],
  ["612", "Transports sur ventes", "expense"],
  ["618", "Autres frais de transport", "expense"],
  ["621", "Sous-traitance generale", "expense"],
  ["622", "Locations et charges locatives", "expense"],
  ["623", "Redevances de credit-bail", "expense"],
  ["624", "Entretien, reparations et maintenance", "expense"],
  ["625", "Primes d'assurance", "expense"],
  ["626", "Etudes, recherches", "expense"],
  ["627", "Publicite, publications, relations publiques", "expense"],
  ["628", "Frais de telecommunications", "expense"],
  ["631", "Frais bancaires", "expense"],
  ["632", "Remunerations d'intermediaires et conseils", "expense"],
  ["633", "Frais de formation du personnel", "expense"],
  ["637", "Personnel exterieur a l'entreprise", "expense"],
  ["638", "Autres charges externes", "expense"],
  ["641", "Impots et taxes directs", "expense"],
  ["645", "Impots et taxes indirects", "expense"],
  ["648", "Autres impots et taxes", "expense"],
  ["651", "Pertes sur creances clients", "expense"],
  ["658", "Charges diverses", "expense"],
  ["661", "Remunerations directes versees au personnel national", "expense"],
  ["662", "Remunerations directes personnel non national", "expense"],
  ["664", "Charges sociales", "expense"],
  ["668", "Autres charges sociales", "expense"],
  ["671", "Interets des emprunts", "expense"],
  ["673", "Escomptes accordes", "expense"],
  ["676", "Pertes de change", "expense"],
  ["681", "Dotations aux amortissements d'exploitation", "expense"],
  ["691", "Dotations aux provisions d'exploitation", "expense"],
  ["697", "Dotations aux provisions financieres", "expense"],
  ["701", "Ventes de marchandises", "revenue"],
  ["702", "Ventes de produits finis", "revenue"],
  ["703", "Ventes de produits intermediaires", "revenue"],
  ["704", "Ventes de produits residuels", "revenue"],
  ["705", "Travaux factures", "revenue"],
  ["706", "Services vendus", "revenue"],
  ["707", "Produits accessoires", "revenue"],
  ["718", "Autres subventions d'exploitation", "revenue"],
  ["721", "Production immobilisee incorporelle", "revenue"],
  ["722", "Production immobilisee corporelle", "revenue"],
  ["734", "Variations des produits en cours", "revenue"],
  ["736", "Variations des stocks de produits finis", "revenue"],
  ["758", "Produits divers", "revenue"],
  ["771", "Interets de prets", "revenue"],
  ["772", "Revenus de participations", "revenue"],
  ["773", "Escomptes obtenus", "revenue"],
  ["776", "Gains de change", "revenue"],
  ["781", "Transferts de charges d'exploitation", "revenue"],
  ["791", "Reprises de provisions d'exploitation", "revenue"],
  ["797", "Reprises de provisions financieres", "revenue"],
  ["811", "Valeur comptable cessions immobilisations incorporelles", "expense"],
  ["812", "Valeur comptable cessions immobilisations corporelles", "expense"],
  ["821", "Produits des cessions immobilisations incorporelles", "revenue"],
  ["822", "Produits des cessions immobilisations corporelles", "revenue"],
  ["831", "Charges HAO constatees", "expense"],
  ["841", "Produits HAO constates", "revenue"],
  ["871", "Participation legale aux benefices", "expense"],
  ["891", "Impots sur les benefices de l'exercice", "expense"],
  ["1013", "Capital souscrit appele verse non amorti", "equity"],
  ["1014", "Capital souscrit appele verse amorti", "equity"],
  ["1611", "Emprunts obligataires ordinaires", "liability"],
  ["1621", "Emprunts aupres des etablissements de credit", "liability"],
  ["1651", "Depots recus", "liability"],
  ["1652", "Cautionnements recus", "liability"],
  ["2011", "Frais de constitution", "asset"],
  ["2131", "Logiciels acquis", "asset"],
  ["2221", "Terrains nus", "asset"],
  ["2311", "Batiments industriels", "asset"],
  ["2341", "Installations techniques", "asset"],
  ["2351", "Amenagements de bureaux", "asset"],
  ["2411", "Materiel et outillage industriel", "asset"],
  ["2441", "Materiel de bureau", "asset"],
  ["2442", "Mobilier de bureau", "asset"],
  ["2451", "Materiel automobile", "asset"],
  ["2813", "Amortissements des logiciels", "contra_asset"],
  ["2844", "Amortissements du materiel et mobilier", "contra_asset"],
  ["3111", "Marchandises A", "asset"],
  ["3341", "Fournitures de bureau", "asset"],
  ["4011", "Fournisseurs", "liability"],
  ["4012", "Fournisseurs groupe", "liability"],
  ["4017", "Fournisseurs sous-traitants", "liability"],
  ["4081", "Fournisseurs, factures non parvenues", "liability"],
  ["4111", "Clients", "asset"],
  ["4112", "Clients groupe", "asset"],
  ["4161", "Creances clients litigieuses", "asset"],
  ["4181", "Clients, produits a recevoir", "asset"],
  ["4191", "Clients crediteurs", "liability"],
  ["4211", "Personnel, avances et acomptes", "asset"],
  ["4221", "Personnel, remunerations dues", "liability"],
  ["4311", "Securite sociale", "liability"],
  ["4331", "Autres organismes sociaux", "liability"],
  ["4411", "Etat, impot sur les benefices", "liability"],
  ["4431", "TVA facturee sur ventes", "liability"],
  ["4432", "TVA facturee sur prestations de services", "liability"],
  ["4451", "TVA recuperable sur immobilisations", "asset"],
  ["4452", "TVA recuperable sur achats", "asset"],
  ["4454", "TVA recuperable sur services exterieurs", "asset"],
  ["4471", "Impots retenus a la source", "liability"],
  ["4711", "Comptes d'attente debiteurs", "asset"],
  ["4761", "Charges constatees d'avance", "asset"],
  ["4771", "Produits constates d'avance", "liability"],
  ["4811", "Fournisseurs d'investissements", "liability"],
  ["4911", "Depreciations des comptes clients", "contra_asset"],
  ["5011", "Titres du Tresor court terme", "asset"],
  ["5111", "Effets a encaisser", "asset"],
  ["5131", "Cheques a encaisser", "asset"],
  ["5211", "Banques locales", "asset"],
  ["5212", "Banques autres comptes locaux", "asset"],
  ["5311", "Cheques postaux", "asset"],
  ["5611", "Credits de tresorerie", "liability"],
  ["5711", "Caisse en monnaie locale", "asset"],
  ["5712", "Caisse en devises", "asset"],
  ["5811", "Regies d'avance", "asset"],
  ["5851", "Virements de fonds", "asset"],
  ["6011", "Achats de marchandises dans la region", "expense"],
  ["6012", "Achats de marchandises hors region", "expense"],
  ["6019", "Rabais remises ristournes obtenus sur achats", "expense"],
  ["6021", "Achats de matieres premieres dans la region", "expense"],
  ["6031", "Variations des stocks de marchandises", "expense"],
  ["6041", "Achats stockes de matieres consommables", "expense"],
  ["6051", "Fournitures non stockables", "expense"],
  ["6081", "Achats d'emballages perdus", "expense"],
  ["6111", "Transports sur achats", "expense"],
  ["6121", "Transports sur ventes", "expense"],
  ["6181", "Autres frais de transport", "expense"],
  ["6211", "Sous-traitance generale", "expense"],
  ["6221", "Locations de terrains", "expense"],
  ["6222", "Locations de batiments", "expense"],
  ["6223", "Locations de materiels et outillages", "expense"],
  ["6228", "Locations et charges locatives diverses", "expense"],
  ["6231", "Redevances de credit-bail immobilier", "expense"],
  ["6241", "Entretien et reparations", "expense"],
  ["6251", "Primes d'assurance", "expense"],
  ["6261", "Etudes et recherches", "expense"],
  ["6271", "Publicite et publications", "expense"],
  ["6281", "Frais de telecommunications", "expense"],
  ["6311", "Frais sur titres", "expense"],
  ["6312", "Frais sur effets", "expense"],
  ["6318", "Autres frais bancaires", "expense"],
  ["6321", "Honoraires et conseils", "expense"],
  ["6331", "Frais de formation du personnel", "expense"],
  ["6371", "Personnel interimaire", "expense"],
  ["6381", "Autres charges externes", "expense"],
  ["6411", "Impots et taxes directs", "expense"],
  ["6451", "Impots et taxes indirects", "expense"],
  ["6481", "Autres impots et taxes", "expense"],
  ["6511", "Pertes sur creances clients", "expense"],
  ["6581", "Charges diverses", "expense"],
  ["6611", "Appointements salaires et commissions", "expense"],
  ["6612", "Primes et gratifications", "expense"],
  ["6613", "Conges payes", "expense"],
  ["6618", "Autres remunerations directes", "expense"],
  ["6641", "Charges sociales personnel national", "expense"],
  ["6642", "Charges sociales personnel non national", "expense"],
  ["6681", "Autres charges sociales", "expense"],
  ["6711", "Interets des emprunts", "expense"],
  ["6731", "Escomptes accordes", "expense"],
  ["6761", "Pertes de change", "expense"],
  ["6811", "Dotations aux amortissements d'exploitation", "expense"],
  ["6911", "Dotations aux provisions d'exploitation", "expense"],
  ["6971", "Dotations aux provisions financieres", "expense"],
  ["7011", "Ventes de marchandises dans la region", "revenue"],
  ["7012", "Ventes de marchandises hors region", "revenue"],
  ["7021", "Ventes de produits finis dans la region", "revenue"],
  ["7051", "Travaux factures", "revenue"],
  ["7061", "Services vendus dans la region", "revenue"],
  ["7062", "Services vendus hors region", "revenue"],
  ["7071", "Produits accessoires", "revenue"],
  ["7181", "Autres subventions d'exploitation", "revenue"],
  ["7211", "Production immobilisee incorporelle", "revenue"],
  ["7221", "Production immobilisee corporelle", "revenue"],
  ["7341", "Variations des produits en cours", "revenue"],
  ["7361", "Variations des stocks de produits finis", "revenue"],
  ["7581", "Produits divers", "revenue"],
  ["7711", "Interets de prets", "revenue"],
  ["7731", "Escomptes obtenus", "revenue"],
  ["7761", "Gains de change", "revenue"],
  ["7811", "Transferts de charges d'exploitation", "revenue"],
  ["7911", "Reprises de provisions d'exploitation", "revenue"],
  ["7971", "Reprises de provisions financieres", "revenue"],
  ["8111", "Valeur comptable cessions immobilisations incorporelles", "expense"],
  ["8121", "Valeur comptable cessions immobilisations corporelles", "expense"],
  ["8211", "Produits cessions immobilisations incorporelles", "revenue"],
  ["8221", "Produits cessions immobilisations corporelles", "revenue"],
  ["8311", "Charges HAO constatees", "expense"],
  ["8411", "Produits HAO constates", "revenue"],
  ["8711", "Participation legale aux benefices", "expense"],
  ["8911", "Impots sur les benefices", "expense"]
];

export const accounts = [...accountGroups, ...detailedAccounts]
  .map(([code, label, type]) => enrichAccount({ code, label, type }))
  .sort((a, b) => a.code.localeCompare(b.code, "fr", { numeric: true }));

export const accountByCode = new Map(accounts.map((account) => [account.code, account]));

export function buildAccountCatalog(customAccounts = []) {
  const merged = new Map(accounts.map((account) => [account.code, account]));
  for (const account of customAccounts) {
    merged.set(account.code, enrichAccount({ ...account, source: "custom" }));
  }
  return [...merged.values()].sort((a, b) => a.code.localeCompare(b.code, "fr", { numeric: true }));
}

export function inferAccountType(code) {
  const account = accountByCode.get(String(code));
  if (account) return normalizeReportType(account.type);

  return normalizeReportType(inferRawAccountType(code));
}

export function enrichAccount(account) {
  const classCode = account.code.at(0);
  const groupCode = account.code.slice(0, 2);
  const accountClass = accountClasses.find((candidate) => candidate.code === classCode);
  const group = accountGroups.find(([code]) => code === groupCode);

  return {
    ...account,
    isPostable: account.code.length === 4,
    reportType: normalizeReportType(account.type),
    classCode,
    classLabel: accountClass?.label ?? "Non classe",
    groupCode,
    groupLabel: group?.[1] ?? accountClass?.label ?? "Non classe",
    source: account.source ?? "SYSCOHADA PDF"
  };
}

function inferRawAccountType(code) {
  const value = String(code);
  const prefix = value.slice(0, 2);
  const firstDigit = value.at(0);

  if (["16", "17", "18", "19", "40", "42", "43", "44", "46", "56"].includes(prefix))
    return "liability";
  if (["28", "29", "39", "49", "59"].includes(prefix)) return "contra_asset";
  if (firstDigit === "1") return "equity";
  if (["2", "3", "4", "5"].includes(firstDigit)) return "asset";
  if (["6"].includes(firstDigit)) return "expense";
  if (["7"].includes(firstDigit)) return "revenue";
  if (firstDigit === "8") return Number(value.slice(0, 2)) % 2 === 0 ? "revenue" : "expense";
  if (firstDigit === "9") return "off_balance";

  return "unknown";
}

function normalizeReportType(type) {
  return (
    {
      contra_asset: "asset",
      contra_equity: "equity"
    }[type] ?? type
  );
}
